/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Demo: typeof import('./src/components/Demo.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Terminal: typeof import('primevue/terminal')['default']
  }
}
