// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function DoChat(arg1:Array<types.Message>):Promise<string>;

export function Greet(arg1:string):Promise<string>;
